:toc: macro
toc::[]

= devon4j Getting Started

== 1. first steps
Here you get to know the basics of devon4j and the app _May-Thai-Star_.

- link:devon4j-overview[**devon4j overview**]
- link:an-devon4j-application[**an devon4j application**]

== 2. devon4j build your own application
In these chapters you will get to know the extension app of _May-Thai-Star_ _JumptheQueue_ and start to get it up and running.

- link:build-devon4j-application[**build your own devon4j application**]
- link:devon4j-components[**application components**]

== 3. devon4j advanced knowledge
The structur of our devon4j project is shown here.

- link:devon4j-layers[**devon4j details**]

== 4. devon4j expand your app
We extend our app and test the functionallity with a tool. We will also prove that the data used meets the practice requirements.

- link:devon4j-adding-custom-functionality[**adding custom functionality**]
- link:devon4j-validations[**data validations**]

== 5. devon4j test and deploy your app
These chapters give a glimpse into the possibilities of devon4j to test an app and finally create a .war file.

- link:devon4j-testing[**testing**]
- link:devon4j-deployment[**deployment**]




