[preface]
== Document Description
This document contains high-level documentation of the components of devonfw to develop a client-server system based on Java and AngularJS. It is intended for individual training as well as for organized training sessions.

:leveloffset: 0
:toc:

= Jump The Queue
== Guide to the Reader

While the document a comprehensive overview, the following links should provide you a step by step navigation to follow the tutorial. The document is structured in an alternating fashion documenting general explanation of the different components followed by the guide of developing the *Jump The Queue* application. The links provided in the following will just point at the beginning of the guide of each section as a shortcut. If you are unsure about anything, please scroll some pages back to find further explanation on the architecture and contents or don't hesitate to ask your trainer if you are currently in a training.

xref:JumpTheQueueDesign#Introduction[Indtroduction]

:leveloffset: 1
include::JumpTheQueueDesign[]

:leveloffset: 0
= OASP4J Getting Started

:leveloffset: 1
include::OASPintro[]

include::OASP4JOverview[]

include::devonfwintro[]

include::AnOASP4jApplication[]

include::BuildOASP4Japplication[]

include::OASP4jComponents[]

include::OASP4jLayers[]

include::OASP4jAddingCustomFunctionality[]

include::OASP4jValidations[]

include::OASP4jTesting[]

include::OASP4jDeployment[]

:leveloffset: 0
= OASP4JS Getting Started

:leveloffset: 1

include::OASPIntro[]

include::OASP4JsIntroduction[]

include::AnOASP4JsApplication[]

include::BuildOASP4JsApplication[]

include::AngularComponents[]

include::AngularServices[]

include::AngularDeployment[]

